#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.

menuentry "Windows (EFI BootNext)" {
    search --no-floppy --fs-uuid --set=root 4d0b1d22-9f3a-42af-8e6c-60125392ece2
    linux /vmlinuz bootnext=0007
    initrd /initrd.img
}
