#!/bin/sh
set -e

if [ "$1" = "configure" ]; then
    # Clean up old initramfs paths from versions prior to 0.2.0
    rm -f /etc/initramfs-tools/hooks/efibootnext
    rm -f /etc/initramfs-tools/scripts/init-premount/efibootnext
    rm -f /usr/share/initramfs-tools/hooks/efibootnext
    rm -f /usr/share/initramfs-tools/scripts/init-premount/efibootnext

    update-grub || true
fi

#DEBHELPER#
