#!/bin/sh
# Derived from initramfs-tools-core's /usr/share/initramfs-tools/hooks/thermal (GPL-2.0-or-later), compatible with GPL-3.0-or-later.
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026  Thomas Grainger <tagrain@gmail.com>
#
# efibootnext is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# efibootnext is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with efibootnext.  If not, see <https://www.gnu.org/licenses/>.
set -e
PREREQ=""
prereqs() { echo "$PREREQ"; }
case "$1" in prereqs) prereqs; exit 0;; esac

. /usr/share/initramfs-tools/hook-functions

[ "${verbose}" = "y" ] && echo "I: efibootnext: copying efibootmgr"
copy_exec "$(command -v efibootmgr)"
