#!/bin/sh
# Derived from initramfs-tools (GPL-2.0-or-later), compatible with GPL-3.0-or-later.
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026  Thomas Grainger <tagrain@gmail.com>
#
# efibootnext is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# efibootnext is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with efibootnext.  If not, see <https://www.gnu.org/licenses/>.
set -e
PREREQ=""
prereqs() { echo "$PREREQ"; }
case "$1" in prereqs) prereqs; exit 0;; esac

BOOTNEXT=""
for param in $(cat /proc/cmdline); do
    case "$param" in
        bootnext=*) BOOTNEXT="${param#bootnext=}" ;;
    esac
done

[ -n "$BOOTNEXT" ] || exit 0

case "$BOOTNEXT" in
    [0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]) ;;
    *) echo "efibootnext: invalid bootnext value: $BOOTNEXT" >&2; exit 1 ;;
esac

if ! mountpoint -q /sys/firmware/efi/efivars; then
    mount -t efivarfs efivarfs /sys/firmware/efi/efivars
fi

if ! efibootmgr --bootnext "$BOOTNEXT"; then
    echo "efibootnext: failed to set BootNext to $BOOTNEXT, continuing normal boot" >&2
    exit 0
fi
reboot -f
