#!/bin/sh
# Derived from initramfs-tools (GPL-2.0-or-later), compatible with GPL-3.0-or-later.
# SPDX-License-Identifier: GPL-3.0-or-later
set -e
PREREQ=""
prereqs() { echo "$PREREQ"; }
case "$1" in prereqs) prereqs; exit 0;; esac

. /usr/share/initramfs-tools/hook-functions

[ "${verbose}" = "y" ] && echo "I: efibootnext: copying efibootmgr"
copy_exec "$(command -v efibootmgr)"
